### ISSUE TITLE
Cannot use QueryBuilder

### ISSUE THREAD

**Issue by florianmari** [JanGorman/Chester#2]
Hey

When I import your lib I can't use the QueryBuilder I'm on XCode 8.0 / iOS 10

I've tried with Carthage and Pods

<img width="581" alt="capture d ecran 2016-10-20 a 14 13 15" src="https://cloud.githubusercontent.com/assets/1582796/19561181/78f944aa-96cf-11e6-9287-37c67adc56ba.png">

**Comment by JanGorman** [comment]
You're right – this Swift 3 `open` vs. `public` mess. Latest push to master should fix it.
